### ISSUE TITLE
TimeSpans not performing as expected with Float32 sample_rate

### ISSUE THREAD

**Issue by mich11** [beacon-biosignals/TimeSpans.jl#15]
I'm having an issue using TimeSpans to view subests of data where it doesn't always return the same number of samples.  For example f I'm looking for a ten-second window of data, from data sampled at 200Hz, most of the time I get 2000 samples, but occasionally it returns 1999 or 2001 samples. Then I noticed that if I call `index_from_time` with a `sample_rate` whose type is `Float32`, I can reproduce the behavior. 

```
tstart = Nanosecond((2*60+20)*1e9)
tend = Nanosecond((2*60+30)*1e9)

index_from_time(Int64(200.0), TimeSpan(tstart, tend))
28001:30000
index_from_time(Float64(200.0), TimeSpan(tstart, tend))
28001:30000
index_from_time(Float32(200.0), TimeSpan(tstart, tend))
28001:29999
```

I now know to convert `sample_rate` to `Float64`, but wanted to mention the problem in case others run into the same thing.

**Comment by omus** [comment]
What we have here is a classic floating point precision issue:
```julia
julia> using TimeSpans, Dates

julia> index_from_time(Float64(200.0),Nanosecond(150000000000))
30001

julia> index_from_time(Float32(200.0), Nanosecond(150000000000))
30000
```
Extracting the internals of `index_from_time` and doing some inlining results in this code:
```julia
julia> time_in_nanoseconds = 150_000_000_000
150000000000

julia> floor(Int, time_in_nanoseconds / (inv(Float64(200)) * 1_000_000_000)) + 1
30001

julia> floor(Int, time_in_nanoseconds / (inv(Float32(200)) * 1_000_000_000)) + 1
30000
```
Due to how `Float32` and `Int64` promotion work and that working with larger floating point values can lead to imprecise results we run into our problem:

```julia
julia> promote_rule(Float32, Int64)
Float32

julia> promote(time_in_nanoseconds, inv(Float32(200)) * 1_000_000_000)
(1.5f11, 5.0f6)

julia> 1.5f11 / 5.0f6
29999.998f0
```
The solution is to refactor our math to work with smaller values which should result in less issues with precision:
```julia
julia> floor(Int, (time_in_nanoseconds / 10^9) * Float64(200)) + 1
30001

julia> floor(Int, (time_in_nanoseconds / 10^9) * Float32(200)) + 1
30001
```
Even in an impossible situation where we force the division to use `Float32` we still don't see the issue for this case:
```julia
julia> floor(Int, (Float32(time_in_nanoseconds) / 10^9) * Float32(200)) + 1
30001
```
